---
- name: Check if stowsh is installed (Ubuntu)
  stat: 
    path: "/usr/local/stowsh-{{ stowsh_ver }}"
  register: stowsh_check
- name: Skipping stowsh (Ubuntu)
  debug:
    msg: "stowsh is already installed. Skipping this tasklist."
  when: stowsh_check.stat.exists
- name: Install stowsh (Ubuntu)
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_stowsh'
    register: stowsh_staging_dir
  - name: Download stowsh (Ubuntu)
    get_url:
      url: "{{ stowsh_url }}"
      dest: "{{ stowsh_staging_dir.path }}/stowsh-{{ stowsh_ver }}.tar.gz"
  - name: Create content folder (Ubuntu)
    file:
      path: "{{ stowsh_staging_dir.path }}/content"
      state: directory 
  - name: Unarchive stowsh (Ubuntu)
    unarchive:
      src: "{{ stowsh_staging_dir.path }}/stowsh-{{ stowsh_ver }}.tar.gz"
      dest: "{{ stowsh_staging_dir.path }}/content"
      copy: no
  - name: Install stowsh (Ubuntu)
    command: "mv {{ stowsh_staging_dir.path }}/content /usr/local/stowsh-{{ stowsh_ver }}"
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ stowsh_staging_dir.path }}"
      state: absent
  when: not stowsh_check.stat.exists
  become: yes
