---
- name: Install Dotnet (Ubuntu)
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_dotnet'
    register: dotnet_staging_dir
  - name: Download key (Ubuntu)
    uri:
      url: "{{ dotnet_key_url }}"
      dest: "{{ dotnet_staging_dir.path }}/dotnet_key.deb"
  - name: Install key (Ubuntu)
    apt:
      deb: "{{ dotnet_staging_dir.path }}/dotnet_key.deb"
    become: yes
  - name: Add repository
    apt_repository:
      repo: "deb {{ dotnet_ubuntu_archive_url }} {{ ansible_distribution_release }} {{ dotnet_apt_repo }}"
      state: present
  - name: Install apt-transport-https
    apt:
      name: 'apt-transport-https'
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install Dotnet SDK
    apt:
      name: "dotnet-sdk-{{ dotnet_ver }}"
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ dotnet_staging_dir.path }}"
      state: absent
