---
- name: Check if Dotnet is installed (Ubuntu)
  block:
  - name: "Grab dotnet version."
    command: 'dotnet --version'
    register: dotnet_version_check
  - name: "Currently installed dotnet version"
    debug:
      msg: "{{ dotnet_version_check.stdout }}"
  - name: "Verify dotnet version."
    set_fact:
      dotnet_version_verify: "{{ dotnet.ver in dotnet_version_check.stdout[:dotnet.ver|length] }}"
- name: Skipping Dotnet (Ubuntu)
  debug:
    msg: "Dotnet is already installed. Skipping this tasklist."
  when: dotnet_version_verify
- name: Install Dotnet (Ubuntu)
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_dotnet'
    register: dotnet_staging_dir
  - name: Download key (Ubuntu)
    uri:
      url: "{{ dotnet.apt.key.url }}"
      dest: "{{ dotnet_staging_dir.path }}/dotnet.key.deb"
  - name: Install key (Ubuntu)
    apt:
      deb: "{{ dotnet_staging_dir.path }}/dotnet.key.deb"
    become: yes
  - name: Add repository
    apt_repository:
      repo: "deb {{ dotnet.apt.archive.url }} {{ ansible_distribution_release }} {{ dotnet.apt.repo }}"
      state: present
  - name: Install apt-transport-https
    apt:
      name: 'apt-transport-https'
  - name: Update apt cache
    apt:
      update_cache: yes
  - name: Install Dotnet SDK
    apt:
      name: "dotnet-sdk-{{ dotnet.ver }}"
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ dotnet_staging_dir.path }}"
      state: absent
  when: not dotnet_version_verify
