---
- name: Check if Visual Studio Code is installed
  stat: 
    path: /Applications/Visual Studio Code.app/ 
  register: vscode
- name: Skipping Visual Studio Code install 
  debug:
    msg: "Visual Studio Code is already installed. Skipping this tasklist." 
  when: vscode.stat.exists
- name: Install Visual Studio Code
  block:
    - name: Brew Cask Install Visual Studio Code 
      homebrew_cask:
        name: visual-studio-code
        state: present
  when: not vscode.stat.exists
