---
- name: Create infra-init.sh profile script
  template:
    src: infra-init.sh.j2
    dest: "{{ profile.init.path }}"
  vars:
    go_path: "${HOME}"
    go_root: "{{ go_dir }}"
    jdk_home: "{{ jdk_dir }}"
    kubectl_bin: "{{ kubectl_dir }}/bin"
    mvn_home: "{{ mvn_dir }}"
    stowsh_bin: "{{ stowsh_dir }}/bin"
  tags:
  - profile
