---
- name: Create profile script
  ansible.builtin.template:
    dest: /etc/profile.d/00-cjvdev.sh
    mode: "0755"
    src: roles/cjvdev/templates/00-cjvdev.sh.j2
  become: true
  tags:
    - cjvdev

- name: General utilities
  ansible.builtin.apt:
    name:
      - ethtool
      - net-tools
  become: true
  tags:
    - cjvdev
