---
- name: wsl_ubuntu_localhost | Ubuntu on WSL
  hosts: wsl_ubuntu_localhost
  roles:
  - aws
  - bats
  - stowsh
  - java
  - dotnet
  - docker
  - hugo
  - R
  - go
  - k8s
  - wsl
  - profile
  vars:
    aws_cli_installer_url: "{{ aws.cli.installer.url }}"
    bats_ver: "{{ bats.ver }}"
    bats_dir: "/usr/local/bats-{{ bats.ver }}"
    bats_key_filepath: "/home/{{ managed_user }}/.ssh/id_rsa"
    utility_packages: "{{ wsl.utility.packages }}"
    go_checksum: "{{ go.checksum }}"
    go_dir: "/usr/local/go-{{ go.ver }}"
    hugo_ver: "{{ hugo.ver }}"
    hugo_bin: "/usr/local/hugo-{{ hugo.ver }}/bin"
    go_ver: "{{ go.ver }}"
    jdk_dir: "/usr/local/openjdk-{{ jdk.ver }}"
    kubectl_dir: "/usr/local/kubectl-{{ k8s.kubectl.ver }}"
    mvn_dir: "/usr/local/apache-maven-{{ mvn.ver }}"
    r_libs_user: "/home/{{ managed_user }}/.Rlibs/{{ r.ver }}"
    stowsh_dir: "/usr/local/stowsh-{{ stowsh.ver }}"
