---
- name: Install GPG keyring
  ansible.builtin.apt_key:
    keyring: "{{ keyring_path }}"
    url: https://nvidia.github.io/libnvidia-container/gpgkey
  become: true

- name: Setup NVIDIA Container Toolkit repo
  ansible.builtin.apt_repository:
    filename: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    repo: |
      deb [signed-by={{ keyring_path }}] https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
  become: true

- name: Install Latest nvidia-container-toolkit
  ansible.builtin.apt:
    name:
      - nvidia-docker2
  become: true
