---
- name: Install bats (Ubuntu)
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_bats'
    register: bats_staging_dir
  - name: Clone repo
    git:
      repo: 'ssh://git@github.com/sstephenson/bats.git'
      dest: "{{ bats_staging_dir.path }}"
      version: "{{ bats_ver }}"
      key_file: "{{ bats_key_filepath }}"
  - name: Ensure bats_dir exists (Ubuntu)
    file:
      path: "{{ bats_dir }}"
      state: directory
  - name: Run install script
    command: "{{ bats_staging_dir.path}}/install.sh {{ bats_dir}}"
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ bats_staging_dir.path }}"
      state: absent
  become: yes
