---
- name: Install bats (Ubuntu)
  block:
  - name: Create staging directory (Ubuntu)
    ansible.builtin.tempfile:
      state: directory
      suffix: '_bats'
    register: bats_staging_dir
  - name: Unarchive artifact
    ansible.builtin.unarchive:
      remote_src: true
      src: "https://github.com/bats-core/bats-core/archive/refs/tags/v{{ bats.ver }}.tar.gz"
      dest: "{{ bats_staging_dir.path }}"
  - name: Ensure bats_dir exists (Ubuntu)
    file:
      path: "{{ bats_dir }}"
      state: directory
  - name: Run install script
    command: "{{ bats_staging_dir.path}}/bats-core-{{ bats.ver }}/install.sh {{ bats_dir}}"
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ bats_staging_dir.path }}"
      state: absent
  become: yes
  tags:
  - bats
