---
- name: Install aws-cli
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_aws'
    register: aws_staging_dir
  - name: Download aws-cli installer archive
    get_url:
      url: "{{ aws_cli_installer_url }}"
      dest: "{{ aws_staging_dir.path }}/aws-cli.linux-amd64.tar.gz"
  - name: Unzip aws-cli installer
    unarchive:
      src: "{{ aws_staging_dir.path }}/aws-cli.linux-amd64.tar.gz"
      dest: "{{ aws_staging_dir.path }}"
  - name: Run installer
    command:
      cmd: ./install --update
      chdir: "{{ aws_staging_dir.path }}/aws"
    become: yes
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ aws_staging_dir.path }}"
      state: absent
- name: Install boto3
  pip:
    name: boto3==1.12.5
