---
- name: Install NordVPN deb
  ansible.builtin.apt:
    deb: https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb
    update_cache: True
  become: True

- name: Install NordVPN
  ansible.builtin.apt:
    name:
    - nordvpn
  become: True

- name: Checking managed_user (Ubuntu)
  fail:
    msg: 'managed_user variable was not set. You can set this by running the playbook with the --extra-vars option.'
  when: managed_user is not defined

- name: Adding managed_user to NordVPN Group (Ubuntu)
  user:
    groups: nordvpn
    append: True
    name: "{{ managed_user }}"
  become: True
