---
- name: Install JDK (OSX)
  import_tasks: osx_jdk.yml
  when: ansible_distribution == "MacOSX"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Install JDK (Unix)
  import_tasks: unix_jdk.yml
  when: ansible_distribution != "MacOSX"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Download Maven
  get_url:
    url: "http://mirrors.advancedhosters.com/apache/maven/maven-3/{{ mvn_ver }}/binaries/apache-maven-{{ mvn_ver }}-bin.tar.gz"
    dest: "/usr/local/src/apache-maven-{{ mvn_ver }}-bin.tar.gz"
    checksum: "{{ mvn_checksum }}"
  become: yes
- name: Make Maven directory
  file:
    path: "/usr/local/apache-maven-{{ mvn_ver }}"
    state: directory
  become: yes
- name: Install Maven
  unarchive:
    src: "/usr/local/src/apache-maven-{{ mvn_ver }}-bin.tar.gz"
    dest: "/usr/local/"
    copy: no
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
- name: Cleanup Maven Tarball
  file:
    path: "/usr/local/src/apache-maven-{{ mvn_ver }}-bin.tar.gz"
    state: absent
  become: yes
