---
- name: Install JDK (OSX)
  import_tasks: osx_jdk.yml
  when: ansible_distribution == "MacOSX"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Install JDK (Ubuntu)
  import_tasks: ubuntu_jdk.yml
  when: ansible_distribution == "Ubuntu"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Install JDK (Unix)
  import_tasks: unix_jdk.yml
  when: 
  - ansible_distribution != "MacOSX"
  - ansible_distribution != "Ubuntu"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Check if Maven is installed (Ubuntu)
  stat: 
    path: "{{ mvn_dir }}" 
  register: mvn_check
- name: Skipping Maven (Ubuntu)
  debug:
    msg: "Maven is already installed. Skipping this tasklist."
  when: mvn_check.stat.exists
- name: Install Maven 
  block:
  - name: Create staging directory
    tempfile:
      state: directory
      suffix: '_mvn'
    register: mvn_staging_dir
  - name: Download Maven
    get_url:
      url: "{{ mvn.url }}"
      dest: "{{ mvn_staging_dir.path }}/apache-maven-{{ mvn.ver }}-bin.tar.gz"
      checksum: "{{ mvn.checksum }}"
    become: yes
  - name: Make Maven directory
    file:
      path: "{{ mvn_dir }}"
      state: directory
    become: yes
  - name: Install Maven
    unarchive:
      src: "{{ mvn_staging_dir.path }}/apache-maven-{{ mvn.ver }}-bin.tar.gz"
      dest: "/usr/local/"
      copy: no
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
  always:
  - name: Cleanup staging directory
    file:
      path: "{{ mvn_staging_dir.path }}"
      state: absent
    become: yes
  when: not mvn_check.stat.exists
