---
- name: Check if OpenJDK is installed (OSX)
  stat: 
    path: "/Library/Java/Home"
  register: openjdk
- name: Skipping OpenJDK (OSX)
  debug:
    msg: "OpenJDK is already installed. Skipping this tasklist."
  when: openjdk.stat.exists
- name: Install OpenJDK (OSX)
  block:
  - name: Create staging directory (OSX)
    tempfile:
      state: directory
      suffix: '_openjdk'
    register: openjdk_staging_dir
  - name: Download OpenJDK (OSX)
    get_url:
      url: "{{ jdk.url }}"
      dest: "{{ openjdk_staging_dir.path }}/openjdk-{{ jdk.ver }}.tar.gz"
      checksum: "{{ jdk.checksum }}"
  - name: Create content folder (OSX)
    file:
      path: "{{ openjdk_staging_dir.path }}/content"
      state: directory
  - name: Unarchive OpenJDK (OSX)
    unarchive:
      src: "{{ openjdk_staging_dir.path }}/openjdk-{{ jdk.ver }}.tar.gz"
      dest: "{{ openjdk_staging_dir.path }}/content"
      copy: no
  - name: Install OpenJDK (OSX)
    command: "cp -r {{ openjdk_staging_dir.path }}/content/jdk-{{ jdk.ver }}.jdk/Contents/. /Library/Java/"
  - name: Clean up staging directory (OSX)
    file:
      path: "{{ openjdk_staging_dir.path }}"
      state: absent
  when: not openjdk.stat.exists
  become: yes
