---
- name: Check if OpenJDK is installed (Ubuntu)
  stat: 
    path: "/usr/local/openjdk-{{ jdk_ver }}"
  register: openjdk_check
- name: Skipping OpenJDK (Ubuntu)
  debug:
    msg: "OpenJDK is already installed. Skipping this tasklist."
  when: openjdk_check.stat.exists
- name: Install OpenJDK (Ubuntu)
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_openjdk'
    register: openjdk_staging_dir
  - name: Download OpenJDK (Ubuntu)
    get_url:
      url: "{{ jdk_url }}"
      dest: "{{ openjdk_staging_dir.path }}/openjdk-{{ jdk_ver }}.tar.gz"
      checksum: "{{ jdk_checksum }}"
  - name: Create content folder (Ubuntu)
    file:
      path: "{{ openjdk_staging_dir.path }}/content"
      state: directory 
  - name: Unarchive OpenJDK (Ubuntu)
    unarchive:
      src: "{{ openjdk_staging_dir.path }}/openjdk-{{ jdk_ver }}.tar.gz"
      dest: "{{ openjdk_staging_dir.path }}/content"
      copy: no
  - name: Install OpenJDK (Ubuntu)
    command: "mv {{ openjdk_staging_dir.path }}/content/jdk-{{ jdk_ver }} /usr/local/openjdk-{{ jdk_ver }}"
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ openjdk_staging_dir.path }}"
      state: absent
  when: not openjdk_check.stat.exists
  become: yes
