---
- name: Check if Golang is installed (Ubuntu)
  block:
  - name: Grab go version.
    shell: "{{ go_dir }}/go/bin/go version | cut -d' ' -f3"
    register: go_version_check
  - name: Currently installed go version
    debug:
      msg: "{{ go_version_check.stdout }}"
  - name: "Verify go version."
    set_fact:
      go_version_verify: "{{ go.ver in go_version_check.stdout }}"
- name: Install Golang
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_go'
    register: go_staging_dir
  - name: Download Golang archive
    get_url:
      url: "https://dl.google.com/go/go{{ go_ver }}.linux-amd64.tar.gz"
      dest: "{{ go_staging_dir.path }}/go{{ go_ver }}.linux-amd64.tar.gz"
      checksum: "{{ go_checksum }}"
  - name: Make Golang directory
    file:
      path: "{{ go_dir }}" 
      state: directory
  - name: Install Golang source
    unarchive:
      src: "{{ go_staging_dir.path }}/go{{ go_ver }}.linux-amd64.tar.gz"
      dest: "{{ go_dir }}" 
      copy: no
  - name: Remove Golang archive
    file:
      path: "{{ go_staging_dir.path }}"
      state: absent
  when: not go_version_verify
  become: yes
