---
- name: dkms status rtl88x2bu
  ansible.builtin.command:
    cmd: "dkms status rtl88x2bu"
  notify: install_driver
  changed_when: not dkms_status.stdout or package_version not in dkms_status.stdout
  register: dkms_status
