---
- name: Install Hugo (OSX)
  import_tasks: osx_hugo.yml
  when: ansible_distribution == "MacOSX"
- name: Install Hugo (Ubuntu)
  import_tasks: ubuntu_hugo.yml
  when: ansible_distribution == "Ubuntu"
