---
- name: Install hugo (Ubuntu)
  block:
  - name: Ensure hugo directory exists
    file:
      path: "{{ hugo_bin }}"
      state: directory
  - name: Download and unpack hugo tarball
    unarchive:
      src: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_ver }}/hugo_{{ hugo_ver }}_Linux-64bit.tar.gz"
      remote_src: yes
      dest: "{{ hugo_bin }}"
