---
- name: Check if Docker is installed (Ubuntu)
  block:
  - name: Retrieve docker version
    shell: "dpkg-query --list | grep {{ docker.apt.name }} | awk '{print $3}'"
    register: docker_installed_version
  - name: Currently installed version
    debug:
      msg: "{{ docker_installed_version.stdout }}"
  - name: Compare installed version with configured version
    set_fact:
      docker_version_verify: "{{ docker.ver in docker_installed_version.stdout }}"
- name: Install Docker (Ubuntu)
  block:
  - name: Create staging directory (Ubuntu)
    tempfile:
      state: directory
      suffix: '_docker'
    register: docker_staging_dir
  - name: Download Docker GPG Key (Ubuntu)
    get_url:
      url: "{{ docker.gpg.url }}"
      dest: "{{ docker_staging_dir.path }}/gpg"
  - name: Add Docker GPGP Key (Ubuntu)
    apt_key:
      file: "{{ docker_staging_dir.path }}/gpg"
  - name: Add Docker Repo (Ubuntu)
    apt_repository:
      repo: "{{ docker.repo.archive_type }} {{ docker.repo.url }} {{ ansible_distribution_release }} {{ docker.repo.components | join(' ') }}"
  - name: Update Package List (Ubuntu)
    apt:
      update_cache: yes
  - name: Install Docker (Ubuntu)
    apt:
      name: "{{ docker.apt.name }}"
  always:
  - name: Clean up staging directory (Ubuntu)
    file:
      path: "{{ docker_staging_dir.path }}"
      state: absent
  when: not docker_version_verify
  become: yes
- name: Docker Post-Install (Ubuntu)
  block:
  - name: Add Docker Group (Ubuntu)
    group:
      name: "{{ docker.group.name }}"
      state: present
  - name: Checking managed_user (Ubuntu)
    fail:
      msg: 'managed_user variable was not set. You can set this by running the playbook with the --extra-vars option.'
    when: managed_user is not defined
  - name: Adding managed_user to Docker Group (Ubuntu)
    user:
      groups: "{{ docker.group.name }}"
      append: yes
      name: "{{ managed_user }}"
