---
- name: Download rtl88x2bu source
  ansible.builtin.unarchive:
    dest: "/usr/src/rtl88x2bu-{{ package_version }}"
    mode: "0755"
    remote_src: true
    src: "https://github.com/cilynx/rtl88x2bu/archive/refs/heads/{{ package_version }}_35809.20191129_COEX20191120-7777.zip"
  listen: install_driver
  become: true

- name: Add rtl88x2bu driver
  ansible.builtin.command:
    cmd: "dkms add -m rtl88x2bu -v {{ package_version }}"
  listen: install_driver
  register: install_driver
  become: true

- name: Build rtl88x2bu driver
  ansible.builtin.command:
    cmd: "dkms build -m rtl88x2bu -v {{ package_version }}"
  listen: install_driver
  become: true

- name: Install rtl88x2bu driver
  ansible.builtin.command:
    cmd: "dkms install -m rtl88x2bu -v {{ package_version }}"
  listen: install_driver
  become: true

- name: Modprobe rtl88x2bu driver
  ansible.builtin.modprobe:
    name: 88x2bu
  listen: install_driver
  become: true
