---
- name: Checking HOME (Ubuntu)
  ansible.builtin.assert:
    that:
      - lookup('ansible.builtin.env', 'HOME') | length > 0
    fail_msg: 'HOME environment variable was not set. This is needed so the play knows where to place the systemd_start.sh script.'

- name: Create systemd_start.sh script
  ansible.builtin.template:
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/bin/systemd_start.sh" 
    mode: 0755
    src: templates/systemd_start.sh.j2
  become: True
  tags:
  - cjvdev_wsl

- name: Install cjvdev
  ansible.builtin.include_tasks:
    file: roles/cjvdev/tasks/install_cjvdev.yml
    apply:
      tags:
      - cjvdev_wsl
  vars:
    clconf_checksum: sha256:2c7ea37e808ef337e43e2a9f2ac1a0c56de5bebd8c8f5a61b6166674f59fe221
    clconf_version: 3.0.3
  tags:
  - cjvdev_wsl

- name: Install gh
  ansible.builtin.include_tasks:
    file: roles/cjvdev/tasks/install_gh.yml
    apply:
      tags:
      - cjvdev_wsl
      - gh
  vars:
    gh_dir: /usr/local/lib/gh
    gh_version: 2.9.0
  tags:
  - cjvdev_wsl
