---
- name: Install nvidia driver
  ansible.builtin.apt:
    name:
    - nvidia-driver-460
  become: True
  tags:
  - moonlight

- name: Remove nvidia blacklist
  # see: https://forums.developer.nvidia.com/t/nvidia-smi-has-failed-because-it-couldn-t-communicate-with-the-nvidia-driver-after-updating-ubuntu-20-04/170985/4
  ansible.builtin.lineinfile:
    line: 'blacklist nvidiafb'
    path: /etc/modprobe.d/blacklist-framebuffer.conf
    state: absent
  become: True
  tags:
  - moonlight

- name: Update initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u
  become: True
  tags:
  - moonlight

- name: Install lightdm
  # nvidia doesn't play nicely with gdm3, need to use lightdm
  # see: https://kupczynski.info/2018/11/18/ubuntu-1810-nvidia-lightdm.html
  ansible.builtin.apt:
    name:
    - lightdm
  become: True
  tags:
  - moonlight

- name: Install moonlight
  community.general.snap:
    name:
    - moonlight
  become: True
  tags:
  - moonlight
