on:
  pull_request:
    types:
    - opened
    - edited
    - reopened
    - synchronize
    - ready_for_review
    branches:
    - main

jobs:
  ansible-lint:
    name: Ansbile Lint
    runes-on: ubuntu:latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ansible-lint
      uses: ansible-community/ansible-lint-action@main
